"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Router_1 = require("./Router");
exports.Router = Router_1.Router;
var RouterOutletMap_1 = require("./RouterOutletMap");
exports.RouterOutletMap = RouterOutletMap_1.RouterOutletMap;
var Config_1 = require("./Config");
exports.ReuseRouteStrategy = Config_1.ReuseRouteStrategy;
var router_ex_module_1 = require("./router-ex.module");
exports.RouterExModule = router_ex_module_1.RouterExModule;
var RouteEvents_1 = require("./RouteEvents");
exports.NavigationCancel = RouteEvents_1.NavigationCancel;
exports.NavigationEnd = RouteEvents_1.NavigationEnd;
exports.NavigationStart = RouteEvents_1.NavigationStart;
var RouteContext_1 = require("./RouteContext");
exports.RouteContext = RouteContext_1.RouteContext;
var RouterModuleFactory_1 = require("./RouterModuleFactory");
exports.RouterModuleFactory = RouterModuleFactory_1.RouterModuleFactory;
var UrlParser_1 = require("./UrlParser");
exports.UrlParser = UrlParser_1.UrlParser;
