import { Injector } from "@angular/core";
import { Location } from "@angular/common";
import { RouteMatchService } from "./RouteMatchService";
import { Observable } from "rxjs/Observable";
import { RouterOutletMap } from "./RouterOutletMap";
import { NavigationExtras, QueryParams } from "./Config";
import { NavigationEvent } from "./RouteEvents";
import { QueryStringParser } from "./QueryStringParser";
export declare class Router {
    private outletMap;
    private matchService;
    private location;
    private injector;
    private queryStringParser;
    private baseHref;
    private resolvedRoutes;
    private locationSubscription;
    private navigationId;
    private currentContext;
    private navigations;
    private navigating;
    constructor(outletMap: RouterOutletMap, matchService: RouteMatchService, location: Location, injector: Injector, queryStringParser: QueryStringParser, baseHref: string);
    readonly queryParamsSnapshot: QueryParams;
    private _queryParams;
    readonly queryParams: Observable<QueryParams>;
    private _events;
    readonly events: Observable<NavigationEvent>;
    private static stripTrailingSlash(url);
    private static urlEquals(url1, url2);
    initialNavigation(): void;
    navigateByUrl(url: string, extras?: NavigationExtras): Promise<any>;
    reload(): Promise<boolean>;
    setQuery(p: QueryParams, navigationExtras?: NavigationExtras): Promise<any>;
    setUpLocationChangeListener(): void;
    updateQuery(p: QueryParams, navigationExtras?: NavigationExtras): Promise<any>;
    private checkDeactivate(currentRoute, injector);
    private checkGuards(newRoute);
    private executeScheduledNavigation({extras, id, url});
    private matchRoute(url, config);
    private navigateInternal(url, extras);
    private processNavigations();
    private resetUrlToCurrent();
    private resolveRoute(originalUrl, route);
    private scheduleNavigation(nav);
}
